['arts & crafts']
['arts & crafts', 'jewellery']
['arts & crafts', 'jewellery', 'bracelets']
['arts & crafts', 'jewellery', 'necklaces']
['arts & crafts', 'jewellery', 'earrings']
['arts & crafts', 'paintings']
['arts & crafts', 'sculptures']
['arts & crafts', 'knick knacks']

['clothing & apparel']
['clothing & apparel', 'for women']
['clothing & apparel', 'for women', 'shirts']
['clothing & apparel', 'for women', 'sweaters']
['clothing & apparel', 'for women', 'shoes']
['clothing & apparel', 'for women', 'shoes', 'sandals']
['clothing & apparel', 'for women', 'shoes', 'sneakers']
['clothing & apparel', 'for women', 'underwear/swimwear']

['clothing & apparel']
['clothing & apparel', 'for men']
['clothing & apparel', 'for men', 'shirts']
['clothing & apparel', 'for men', 'sweaters']
['clothing & apparel', 'for men', 'shoes']
['clothing & apparel', 'for men', 'shoes', 'sandals']
['clothing & apparel', 'for men', 'shoes', 'sneakers']
['clothing & apparel', 'for men', 'underwear/swimwear']

['clothing & apparel']
['clothing & apparel', 'unisex']
['clothing & apparel', 'unisex', 'shirts']
['clothing & apparel', 'unisex', 'sweaters']
['clothing & apparel', 'unisex', 'shoes']
['clothing & apparel', 'unisex', 'shoes', 'sandals']
['clothing & apparel', 'unisex', 'shoes', 'sneakers']
['clothing & apparel', 'unisex', 'underwear/swimwear']

['clothing & apparel', 'hats & scarfs']

['clothing & apparel', 'accessories']
['clothing & apparel', 'accessories', 'masks']
['clothing & apparel', 'accessories', 'sunglasses']
['clothing & apparel', 'accessories', 'bags & knapsacks']

['books & entertainment']
['books & entertainment', 'books']
['books & entertainment', 'books', 'fiction']
['books & entertainment', 'books', 'non-fiction']

['books & entertainment', 'movies']
['books & entertainment', 'movies', 'fiction']
['books & entertainment', 'movies', 'non-fiction']

['books & entertainment', 'music']
['books & entertainment', 'music', 'reggae']
['books & entertainment', 'music', 'dancehall']
['books & entertainment', 'music', 'ska']

['food & drink']
['food & drink', 'sauces & seasoning']
['food & drink', 'coffee']
['food & drink', 'chocolates']
['food & drink', 'herbal supplements']

['miscellaneous']
['miscellaneous', 'home']
['miscellaneous', 'home', 'bedroom']
['miscellaneous', 'home', 'bathroom']
['miscellaneous', 'home', 'living room']
['miscellaneous', 'home', 'kitchen']

['miscellaneous', 'hair']
['miscellaneous', 'hair', 'haircare products']
['miscellaneous', 'hair', 'extensions']

['miscellaneous', 'flags']
['miscellaneous', 'other']

[]

